export const JOBTYPE_LOAD_REQUEST = "JOBTYPE_LOAD_REQUEST";
export const JOBTYPE_LOAD_SUCCESS = "JOBTYPE_LOAD_SUCCESS";
export const JOBTYPE_LOAD_FAIL = "JOBTYPE_LOAD_FAIL";
export const JOBTYPE_LOAD_RESET = "JOBTYPE_LOAD_RESET";

export const CREATE_JOBTYPE_REQUEST = "CREATE_JOBTYPE_REQUEST";
export const CREATE_JOBTYPE_SUCCESS = "CREATE_JOBTYPE_SUCCESS";
export const CREATE_JOBTYPE_FAIL = "CREATE_JOBTYPE_FAIL";
export const CREATE_JOBTYPE_RESET = "CREATE_JOBTYPE_RESET";

export const DELETE_JOBTYPE_REQUEST = "DELETE_JOBTYPE_REQUEST";
export const DELETE_JOBTYPE_SUCCESS = "DELETE_JOBTYPE_SUCCESS";
export const DELETE_JOBTYPE_FAIL = "DELETE_JOBTYPE_FAIL";
export const DELETE_JOBTYPE_RESET = "DELETE_JOBTYPE_RESET";